### ISSUE TITLE
Does not complete container names with docker rm

### ISSUE THREAD

**Issue by ayZagen** [matt9ucci/DockerCompletion#16]
As the title says, container names are not coming up with `docker rm`

Thanks for your work.

**Comment by matt9ucci** [comment]
Thank you for your report! I have tested `docker rm` completions on my machine and it works as follows:

```sh
$ docker ps --all
CONTAINER ID   IMAGE     COMMAND   CREATED          STATUS                        PORTS     NAMES
624c82c9be90   alpine    "sh"      15 minutes ago   Up 15 minutes                           test03
d1d06c60ae03   alpine    "sh"      16 minutes ago   Exited (137) 15 minutes ago             test02
86271f9123e3   alpine    "sh"      16 minutes ago   Exited (137) 15 minutes ago             test01

$ docker rm [press tab, and "test02" and "test01" are completed]

$ docker rm --force [press tab, and "test03", "test02", and "test01" are completed]
```

The first `docker rm` does not remove the running container `test03`. Because of that, DockerCompletion completes only `test01` and `test02`. If we want to complete and remove `test03`, we have to append `--force` option like the second  `docker rm`.

Completer's implementaion:
```
docker container ls --format '{{.Names}}' --filter status=created --filter status=exited

docker container ls --format '{{.Names}}' --all
```

The first command is invoked for `docker rm` which has no option. The result has `created` and `exited` containers' name.

The second command is invoked for `docker rm --force`. The result has all containers' name: `created`, `exited`, `running`, etc.

Would you show me the output of `docker ps --all` and which container names are expected to be completed?

**Comment by matt9ucci** [comment]
Hi @ayZagen. Does that help?

**Comment by ayZagen** [comment]
sorry, I forgot to respond, strangely it works now but at that time it was showing files in the current directory.
